id: A8AA447CA
title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:41:00.953808
  last_modified_at: 2022-03-01 03:41:00.953814
